name: CI/CD For Dev

on:
    push:
      branches:
        - dev
    workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.DEV_AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.DEV_AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.DEV_AWS_REGION }}

      - name: Deploy files to S3 (Dev Bucket)
        run: |
          aws s3 sync ./ s3://${{ secrets.DEV_S3_BUCKET_NAME }} --delete --exclude ".git/*"

      - name: Invalidate CloudFront cache (Dev Distribution)
        run: |
          aws cloudfront create-invalidation \
            --distribution-id ${{ secrets.DEV_CLOUDFRONT_DISTRIBUTION_ID }} \
            --paths "/*"
